class_name CardDefs extends RefCounted

enum CardType {
	NONE,
	GARDENER,           # Player's focus/tool
	BIO_SUBSTRATE,      # Base "land"

	# Tier 0 - Basic Resources
	SPORE_POD,          # Basic seed
	NUTRIENT_SLIME,     # Basic food/energy

	# Tier 1 - Simple Life & Products
	BASIC_FUNGI,        # Grows from Spore Pod + Nutrient
	PROCESSED_NUTRIENTS,# Produced by Fungi

	# Tier 2 - More Complex Life & Interaction Starters
	VINE_SEED,          # Needs Processed Nutrients
	YOUNG_VINE,         # Growing stage
	MATURE_VINE,        # Flowers, needs pollination
	FLUTTERWING_SPORE,  # Basic mobile life seed
	FLUTTERWING_LARVA,  # Grows from spore
	MATURE_FLUTTERWING, # Pollinator

	# Tier 3 - Symbiosis & Advanced Resources
	FERTILIZED_VINE_POD,# Result of pollination
	SYMBIOTIC_ALGAE,    # Grows from Fert. Pod, needs substrate bonus
	LUMINA_CRYSTAL,     # Produced passively by Algae
	GRAZING_SLUG_EGG,   # Needs specific conditions (e.g., near Fungi)
	GRAZING_SLUG,       # Eats Fungi, produces Mulch
	RICH_MULCH,         # Waste product, improves substrate
	FERTILE_SUBSTRATE,  # Upgraded land from Mulch

	# Hazard/Management
	WASTE_TOXIN,        # Generated by imbalance (e.g., too many Slugs)

	# Tier 4 - Goal Components
	APEX_SPORE,         # Rare seed, needs Fertile Substrate + Lumina
	GROWING_APEX,       # Final growth stage
	GENESIS_BLOOM       # Win condition card
}

# Note: Properties defining interactions (eats, produces, needs) added for clarity
const CARD_PROPERTIES = {
	CardType.GARDENER: {"label": "Gardener", "initial_focus": 100.0, "max_focus": 100.0, "action_cost": 50.0, "image": "uid://ca64qvofktjhs"},
	CardType.BIO_SUBSTRATE: {"label": "Bio-Substrate", "image": "uid://dnurxipxp2byb"},

	# Tier 0
	CardType.SPORE_POD: {"label": "Spore Pod", "image": "uid://rl5gjdj5o0gs"},
	CardType.NUTRIENT_SLIME: {"label": "Nutrient Slime", "nutrient_value": 1.0, "image": "uid://swqnh0qcs716"},

	# Tier 1
	CardType.BASIC_FUNGI: {"label": "Basic Fungi", "produces_passively": CardType.PROCESSED_NUTRIENTS, "passive_interval": 15.0, "image": "uid://c8vji67aunfu8"},
	CardType.PROCESSED_NUTRIENTS: {"label": "Processed Nutrients", "nutrient_value": 2.0, "image": "uid://btbyi712xkcgx"},

	# Tier 2
	CardType.VINE_SEED: {"label": "Vine Seed", "needs_nutrient": CardType.PROCESSED_NUTRIENTS, "image": "uid://s33ls1nykkpw"},
	CardType.YOUNG_VINE: {"label": "Young Vine", "needs_nutrient": CardType.PROCESSED_NUTRIENTS, "image": "uid://dkkliydu6w2vh"}, # Needs more nutrients to mature
	CardType.MATURE_VINE: {"label": "Mature Vine", "can_be_pollinated": true, "yields_on_harvest": CardType.NONE, "image": "uid://k4dmtvr1oswe"}, # Maybe yields basic fiber if harvested?
	CardType.FLUTTERWING_SPORE: {"label": "Flutterwing Spore", "needs_nutrient": CardType.NUTRIENT_SLIME, "image": "uid://brf6c82qdpayd"}, # Basic needs
	CardType.FLUTTERWING_LARVA: {"label": "Flutterwing Larva", "image": "uid://bleylu31aj6ut"}, # Simple timed growth
	CardType.MATURE_FLUTTERWING: {"label": "Mature Flutterwing", "is_pollinator": true, "image": "uid://b6y5nt6uucg4u"},

	# Tier 3
	CardType.FERTILIZED_VINE_POD: {"label": "Fertilized Pod", "grows_into": CardType.SYMBIOTIC_ALGAE, "image": "uid://d3858wciwhfeq"},
	CardType.SYMBIOTIC_ALGAE: {"label": "Symbiotic Algae", "produces_passively": CardType.LUMINA_CRYSTAL, "passive_interval": 20.0, "needs_substrate": CardType.FERTILE_SUBSTRATE, "image": "uid://dw2jjnb07cr5k"}, # Needs better soil bonus
	CardType.LUMINA_CRYSTAL: {"label": "Lumina Crystal", "nutrient_value": 5.0, "image": "uid://b060h11gec53l"}, # High energy
	CardType.GRAZING_SLUG_EGG: {"label": "Slug Egg", "needs_nearby": CardType.BASIC_FUNGI, "image": "uid://cce5ok26op7pv"}, # Hatch condition
	CardType.GRAZING_SLUG: {"label": "Grazing Slug", "eats": CardType.BASIC_FUNGI, "produces_passively": CardType.RICH_MULCH, "passive_interval": 10.0, "image": "uid://dbvpmyuo6xwn6"},
	CardType.RICH_MULCH: {"label": "Rich Mulch", "image": "uid://dauqf2l7x2o8r"},
	CardType.FERTILE_SUBSTRATE: {"label": "Fertile Substrate", "image": "uid://cnylnctybitla"},

	# Hazard
	CardType.WASTE_TOXIN: {"label": "Waste Toxin", "inhibits_nearby": true, "image": ""}, # Simple negative effect

	# Tier 4
	CardType.APEX_SPORE: {"label": "Apex Spore", "needs_substrate": CardType.FERTILE_SUBSTRATE, "needs_nutrient": CardType.LUMINA_CRYSTAL, "image": "uid://dg3adgjvowjr3"},
	CardType.GROWING_APEX: {"label": "Growing Apex", "image": "uid://c5pdo423aq3i4"},
	CardType.GENESIS_BLOOM: {"label": "Genesis Bloom\n(Ecosystem Thrives!)", "image": "uid://dj2n50342yvrp"}
}

static func get_label(type: CardType) -> String:
	return get_property(type, "label", "Unknown")

static func get_property(type: CardType, prop_name: String, default_value = null):
	if CARD_PROPERTIES.has(type) and CARD_PROPERTIES[type].has(prop_name):
		return CARD_PROPERTIES[type][prop_name]
	return default_value

# Helper functions for type checking can be useful
static func is_plant(type: CardType) -> bool:
	return type in [CardType.BASIC_FUNGI, CardType.YOUNG_VINE, CardType.MATURE_VINE, CardType.SYMBIOTIC_ALGAE, CardType.GROWING_APEX]
static func is_seed_or_spore(type: CardType) -> bool:
	return type in [CardType.SPORE_POD, CardType.VINE_SEED, CardType.FLUTTERWING_SPORE, CardType.GRAZING_SLUG_EGG, CardType.FERTILIZED_VINE_POD, CardType.APEX_SPORE]
static func is_nutrient(type: CardType) -> bool:
	return type in [CardType.NUTRIENT_SLIME, CardType.PROCESSED_NUTRIENTS, CardType.LUMINA_CRYSTAL]
static func is_creature(type: CardType) -> bool:
	return type in [CardType.FLUTTERWING_LARVA, CardType.MATURE_FLUTTERWING, CardType.GRAZING_SLUG]
static func is_substrate(type: CardType) -> bool:
	return type in [CardType.BIO_SUBSTRATE, CardType.FERTILE_SUBSTRATE]

static func is_seed_spore_or_plant(type: CardType) -> bool:
	return is_plant(type) or is_seed_or_spore(type)
